import { EROUTES, EROUTESSTAGES } from '../../../shared/utils/ERoutes';

export const personStages = [
  { 
      name: 'Начало',  
      id: 0, 
      route: EROUTES.PERSON,
      is_active: true, 
      position: 0, 
      view: 'info', 
      type: 'default',
      url_template: '',
      url_video: '',
      team_file_count: 0, 
      team_videos: [],
  },
  { 
    name: 'Заполни анкету',  
    id: 1, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_FORM}`,
    is_active: true, 
    position: 1, 
    view: 'stage', 
    type: 'default',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Выбор времени для онлайн-мастер-класса',  
    id: 2, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_SCHEDULE}`,
    is_active: true, 
    position: 2, 
    view: 'stage', 
    type: 'default',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Сделайте презентацию',  
    id: 3, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_SLIDES}`,
    is_active: true, 
    position: 3, 
    view: 'stage', 
    type: 'default',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Расписание мастер-классов',  
    id: 4, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_WORKSHOP}`,
    is_active: true, 
    position: 4, 
    view: 'stage', 
    type: 'default',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Оценка работ других участников',  
    id: 5, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_EVALUATE}`,
    is_active: true, 
    position: 5, 
    view: 'stage', 
    type: 'default',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
];

export const personStagesClose = [
  { 
      name: 'Начало',  
      id: 0, 
      route: EROUTES.PERSON,
      is_active: true, 
      position: 0, 
      view: 'info', 
      type: 'default',
      url_template: '',
      url_video: '',
      team_file_count: 0, 
      team_videos: [],
  },
  { 
    name: 'Заполни анкету',  
    id: 1, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_FORM}`,
    is_active: true, 
    position: 1, 
    view: 'stage', 
    type: 'block',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Выбор времени для онлайн-мастер-класса',  
    id: 2, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_SCHEDULE}`,
    is_active: true, 
    position: 2, 
    view: 'stage', 
    type: 'block',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Сделайте презентацию',  
    id: 3, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_SLIDES}`,
    is_active: true, 
    position: 3, 
    view: 'stage', 
    type: 'block',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Расписание мастер-классов',  
    id: 4, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_WORKSHOP}`,
    is_active: true, 
    position: 4, 
    view: 'stage', 
    type: 'block',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
  { 
    name: 'Оценка работ других участников',  
    id: 5, 
    route: `${EROUTES.PERSON}/${EROUTESSTAGES.PERSON_EVALUATE}`,
    is_active: true, 
    position: 5, 
    view: 'stage', 
    type: 'block',
    url_template: '',
    url_video: '',
    team_file_count: 0, 
    team_videos: [],
  },
];
